# Generated by Django 5.1.1 on 2024-10-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
