# Generated by Django 5.1.1 on 2024-10-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_post_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('Software', 'Software'), ('Hardware', 'Hardware'), ('Operating Systems', 'Operating Systems'), ('Networking', 'Networking')], default='None', max_length=100),
        ),
    ]
