# Generated by Django 5.1.1 on 2024-10-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='subject',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
